apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-pod
  template:
    metadata:
      labels:
        app: n8n-pod
    spec:
      containers:
        - image: n8nio/n8n
          name: n8n-pod
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          env:
